<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>icai_crl_bringup_sim</name>
  <version>0.0.0</version>
  <description>Contains launch files for the Gazebo Control Laboratory project</description>
  <maintainer email="dcubillo@comillas.edu">Diego Cubillo</maintainer>
  <license>Apache 2.0</license>
  <author>Diego Cubillo</author>

  <depend>ros_gz</depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>rqt_image_view</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>nav2_map_server</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>

  <exec_depend>icai_crl_description</exec_depend>
  <exec_depend>icai_crl_gazebo</exec_depend>
  <exec_depend>hardware_bridge</exec_depend>
  <exec_depend>rqt_kitt_hmi</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>