---
- ros_topic_name: "front_dist_sensor/scan"
  gz_topic_name: "front_dist_sensor/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "back_dist_sensor/scan"
  gz_topic_name: "back_dist_sensor/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
- ros_topic_name: "imu"
  gz_topic_name: "imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "left_wheel/cmd_volt"
  gz_topic_name: "left_wheel_joint/motor_volt_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "right_wheel/cmd_volt"
  gz_topic_name: "right_wheel_joint/motor_volt_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "left_wheel/voltage"
  gz_topic_name: "left_wheel_joint/motor_voltage"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "right_wheel/voltage"
  gz_topic_name: "right_wheel_joint/motor_voltage"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "left_wheel/ang_velocity"
  gz_topic_name: "left_wheel_joint/joint_velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "right_wheel/ang_velocity"
  gz_topic_name: "right_wheel_joint/joint_velocity"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS
- ros_topic_name: "left_wheel/encoder"
  gz_topic_name: "left_wheel_joint/motor_encoder"
  ros_type_name: "std_msgs/msg/Int32"
  gz_type_name: "gz.msgs.Int32"
  direction: GZ_TO_ROS
- ros_topic_name: "right_wheel/encoder"
  gz_topic_name: "right_wheel_joint/motor_encoder"
  ros_type_name: "std_msgs/msg/Int32"
  gz_type_name: "gz.msgs.Int32"
  direction: GZ_TO_ROS